[c++] Add -Wno-deprecated-declarations for AppleClang
Compilation of Bond on macOS Big Sur 11.2.2 with Xcode 12.4 with Apple
Clang version 12.0.0 (clang-1200.0.32.29) and Boost 1.75.0 fails due to
Boost.Locale's use of the now-depcreated `std::auto_ptr`:

```
In file included from /usr/local/include/boost/locale.hpp:24:
/usr/local/include/boost/locale/util.hpp:203:59: error: 'auto_ptr<boost::locale::util::base_converter>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::locale create_codecvt(std::locale const &in,std::auto_ptr<base_converter> cvt,character_facet_type type);
```

Add `-Wno-deprecated-declarations` to the AppleClang compiler options.
This is what is done for Clang.

Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>